            - name: Download a Build Artifact
  uses: actions/download-artifact@v4.1.2
  l
          

steps:
- uses: actions/download-artifact@v4
- name: Display structure of downloaded files
  run: ls -R
